django_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('forum/', include('forum.urls')),
    path('', RedirectView.as_view(url='/forum/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]

# Используйте static() чтобы добавить соотношения для статических файлов
# Только на период разработки
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

forum/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views
from django.conf.urls import url


urlpatterns = [
    path('', views.ThemeListView.as_view(), name='index'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^change_profile/$', views.change_profile, name='change_profile'),
    url(r'^theme/(?P<pk>\d+)$', views.ThemeDetailView.as_view(), name='theme-detail'),
    url(r'^post/(?P<pk>\d+)$', views.post, name='post-detail'),
    url(r'^post/add/$', login_required(views.PostCreate.as_view()), name='post_create'),
    url(r'^theme/add/$', login_required(views.ThemeCreate.as_view()), name='theme_create'),
    url(r'^post/(?P<pk>\d+)/delete/$', login_required(views.PostDelete.as_view()), name='post_delete'),
    url(r'^theme/(?P<pk>\d+)/delete/$', login_required(views.ThemeDelete.as_view()), name='theme_delete'),
    url(r'^comm/(?P<pk>\d+)/delete/$', login_required(views.CommentDelete.as_view()), name='comm_delete'),
]

forum/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Theme(models.Model):
    name = models.CharField(max_length=200, unique=True, help_text="Введите название темы")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('theme-detail', args=[str(self.id)])


class Post(models.Model):
    theme = models.ForeignKey('Theme', on_delete=models.CASCADE, null=False)
    name = models.CharField(max_length=200, help_text="Введите название поста")
    text = models.TextField(max_length=1000, help_text='Введите пост')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('post-detail', args=[str(self.id)])


class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE, null=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    text = models.TextField(max_length=1000, help_text="Введите комментарий")
    post_time = models.DateTimeField(null=True)

    class Meta:
        ordering = ['post_time']

forum/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class LeaveComm(forms.Form):
    comm = forms.CharField(max_length=200)

    def clean_comm(self):
        data = self.cleaned_data['comm']

        return data


class MyUserCreationForm(UserCreationForm):
    def clean_username(self):
        username = self.cleaned_data["username"]
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("Username already exists")
        return username


class ChangeProfile(forms.Form):
    first_name = forms.CharField(max_length=100, required=False)
    last_name = forms.CharField(max_length=100, required=False)
    email = forms.EmailField(required=False)
    password1 = forms.CharField(max_length=32, required=False, widget=forms.PasswordInput)
    password2 = forms.CharField(max_length=32, required=False, widget=forms.PasswordInput)

    def clean_password2(self):
        password2 = self.cleaned_data['password2']
        return password2

    def clean(self):
        cleaned_data = super(ChangeProfile, self).clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 != password2:
            raise forms.ValidationError('Passwords are not equal')

forum/views.py
from django.views import generic
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
import datetime

from .models import Theme, Post, Comment
from .forms import LeaveComm, MyUserCreationForm, ChangeProfile


class ThemeListView(generic.ListView):
    model = Theme
    paginate_by = 20


class ThemeDetailView(generic.DetailView):
    model = Theme


def post(request, pk):
    comms = Comment.objects.filter(post_id=pk)
    post = Post.objects.get(pk=pk)

    if request.method == 'POST':
        form = LeaveComm(request.POST)

        if form.is_valid():
            comm = Comment()
            comm.author = request.user
            comm.post_id = pk
            comm.post_time = datetime.datetime.now()
            comm.text = form.cleaned_data['comm']
            comm.save()

        return HttpResponseRedirect('/forum/post/%d' % int(pk))

    else:
        form = LeaveComm()

    return render(request, 'post.html', {'form': form, 'comments': comms, 'post': post})


class PostCreate(generic.edit.CreateView):
    model = Post
    fields = '__all__'


class ThemeCreate(generic.edit.CreateView):
    model = Theme
    fields = '__all__'


class PostDelete(generic.edit.DeleteView):
    model = Post
    success_url = '/'


class ThemeDelete(generic.edit.DeleteView):
    model = Theme
    success_url = '/'


class CommentDelete(generic.edit.DeleteView):
    model = Comment
    success_url = '/'


def signup(request):
    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            my_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=my_password)
            login(request, user)
            return redirect('profile')
    else:
        form = MyUserCreationForm()
    return render(request, 'signup.html', {'form': form})


@login_required
def profile(request):
    username = request.user
    first_name = request.user.first_name
    last_name = request.user.last_name
    email = request.user.email

    return render(request, 'profile.html', {'username': username, 'first_name': first_name, 'last_name': last_name,
                                            'email': email})


@login_required
def change_profile(request):
    if request.method == 'POST':
        form = ChangeProfile(request.POST)
        if form.is_valid():
            user = request.user
            if form.cleaned_data['first_name']:
                user.first_name = form.cleaned_data['first_name']
            if form.cleaned_data['last_name']:
                user.last_name = form.cleaned_data['last_name']
            if form.cleaned_data['email']:
                user.email = form.cleaned_data['email']
            if form.cleaned_data['password1']:
                user.set_password(form.cleaned_data['password1'])
            user.save()
            username = form.cleaned_data.get('username')
            my_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=my_password)
            login(request, user)
            return redirect('profile')
    else:
        form = ChangeProfile()
    return render(request, 'change_profile.html', {'form': form})

forum/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block style %} {% endblock %}

    {% block title %}<title>Форум</title>{% endblock %}

    <link rel="shortcut icon" href="https://i.kym-cdn.com/photos/images/newsfeed/000/184/265/70b.png" type="image/png">

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- Добавление дополнительного статического CSS файла -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

<div class="container-fluid">

    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
                <ul class="sidebar-nav">
                    {% if user.is_authenticated %}
                        <li>User: {{ user.get_username }}</li>
                        <li><a href="{% url 'logout'%}?next={{request.path}}">Выход</a></li>
                        <li><a href="{% url 'profile'%}">Профиль</a></li>
                    {% else %}
                        <li><a href="{% url 'login'%}">Вход</a></li>
                        <li><a href="{% url 'signup'%}">Регистрация</a></li>
                    {% endif %}
                    <hr />
                    <li><a href="{% url 'index' %}">Домой</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'post_create' %}">Добавить пост</a></li>
                    {% endif %}
                    {% if perms.forum.add_theme%}
                        <li><a href="{% url 'theme_create' %}">Добавить тему</a></li>
                    {% endif %}
                </ul>
            {% endblock %}
        </div>
        <div class="col-sm-10 ">
            <h1>Форум <img src="https://i.kym-cdn.com/photos/images/newsfeed/000/184/265/70b.png" width="40px", height="40px"></h1>
            {% block content %}{% endblock %}
            {% block pagination %}
                {% if is_paginated %}
                    <div class="pagination">
                        <span class="page-links">
                            {% if page_obj.has_previous %}
                                <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">←</a>
                            {% endif %}
                            <span class="page-current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                            </span>
                            {% if page_obj.has_next %}
                                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">→</a>
                            {% endif %}
                        </span>
                    </div>
                {% endif %}
            {% endblock %}
        </div>
    </div>

</div>
</body>
</html>

forum/templates/change_profile.html
{% extends 'base_generic.html' %}

{% block title %}<title>Изменить профиль</title>{% endblock %}

{% block content %}
    <h2>Изменить данные</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>
{% endblock %}

forum/templates/forum/comment_confirm_delete.html
{% extends "base_generic.html" %}

{% block title %}<title>Удалить комментарий</title>{% endblock %}

{% block content %}

<h1>Удалить комментарий</h1>

<p>Вы хотите удалить комментарий: {{ comment.text }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Да." />
</form>

{% endblock %}

forum/templates/forum/post_confirm_delete.html
{% extends "base_generic.html" %}

{% block title %}<title>Удалить пост</title>{% endblock %}

{% block content %}

<h1>Удалить пост</h1>

<p>Вы хотите удалить пост: {{ post }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Да." />
</form>

{% endblock %}

forum/templates/forum/post_form.html
{% extends "base_generic.html" %}

{% block title %}<title>Добавить пост</title>{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

forum/templates/forum/theme_confirm_delete.html
{% extends "base_generic.html" %}

{% block title %}<title>Удалить тему</title>{% endblock %}

{% block content %}

<h1>Удалить тему</h1>

<p>Вы хотите удалить тему: {{ theme }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Да." />
</form>

{% endblock %}

forum/templates/forum/theme_detail.html
{% extends "base_generic.html" %}

{% block style %}
    <style type="text/css">
        table {
        font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
        font-size: 14px;
        background: white;
        max-width: 70%;
        width: 70%;
        border-collapse: collapse;
        text-align: left;
        }
        th {
        font-weight: normal;
        color: #039;
        border-bottom: 2px solid #6678b1;
        padding: 10px 8px;
        }
        td {
        color: #669;
        border-top: 1px solid #e8edff;
        padding: 10px 15px;
        }
        tr:hover td {background: #e8edff;}
    </style>
{% endblock %}

{% block title %}<title>{{theme.name}}</title>{% endblock %}

{% block content %}
    <a href="{% url 'index' %}">Домой</a> → <a href="{% url 'theme-detail' pk=theme.id %}">{{theme.name}}</a>
    <h1>{{ theme.name }}</h1>

    <div style="margin-left:20px;margin-top:20px">
        <h4>Посты</h4>
        <table>
            <th>Заголовок</th>
            <th>Кол-во сообщений</th>
            <th></th>
            {% for post in theme.post_set.all %}
                <tr>
                    <td>
                        <p><a href="{% url 'post-detail' pk=post.id%}">{{ post.name }}</a></p>
                    </td>
                    <td>
                        <p>{{post.comment_set.count}}</p>
                    </td>
                    <td>
                        {% if perms.forum.delete_post %} <a href="{% url 'post_delete' pk=post.id %}">Удалить</a>{% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}


forum/templates/forum/theme_form.html
{% extends "base_generic.html" %}

{% block title %}<title>Добавить тему</title>{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

forum/templates/forum/theme_list.html
{% extends "base_generic.html" %}

{% block content %}
    <a href="{% url 'index' %}">Home</a>
    <h1>Список тем</h1>
    {% if theme_list %}
        <ul>
        {% for theme in theme_list %}
            <li>
            <a href="{{ theme.get_absolute_url }}">{{ theme.name }}</a>{% if perms.forum.delete_theme %} <a href="{% url 'theme_delete' pk=theme.id %}">Удалить</a> {% endif %}
            </li>
        {% endfor %}

        </ul>

        {% else %}
        <p>Пока тут пусто(</p>
    {% endif %}
{% endblock %}

forum/templates/post.html
{% extends "base_generic.html" %}

{% block title %}<title>{{post.name}}</title>{% endblock %}

{% block content %}
    <a href="{% url 'index' %}">Домой</a> → <a href="{% url 'theme-detail' pk=post.theme_id %}">{{post.theme}}</a> → <a href="{% url 'post-detail' pk=post.id %}">{{post.name}}</a>
    <h1>{{post.name}}</h1>
    <p>{{post.text}}</p>

    <div style="margin-left:20px;margin-top:20px">
        <h4>Ответы</h4>
        {% for comm in comments %}
            <hr />
            <p>{{comm.author}}: {{ comm.text }}   {{comm.post_time}}</p> {% if perms.forum.delete_comment %} <a href="{% url 'comm_delete' pk=comm.id %}">Удалить</a> {% endif %}
        {% endfor %}
    </div>
    {% if request.user.is_authenticated %}
        <form method="post" action="">
            {% csrf_token %}
            <table>
            {{ form }}
            </table>
            <input type="submit" value="Отправить" />
        </form>
    {% endif %}
{% endblock %}

forum/templates/profile.html
{% extends 'base_generic.html' %}

{% block title %}<title>Профиль</title>{% endblock %}

{% block content %}
    <p>Имя пользователя: {{ username }}</p>
    <p>Имя: {{ first_name }}</p>
    <p>Фамилия: {{ last_name }}</p>
    <p>Адрес: {{ email }}</p>
    <a href="{% url 'change_profile' %}" style="border: 1px solid #333; display: inline-block; padding: 5px 15px;
                                                text-decoration: none; color: #000;"> Изменить данные</a>

{% endblock %}


forum/templates/signup.html
{% extends 'base_generic.html' %}

{% block title %}<title>Регистрация</title>{% endblock %}

{% block content %}
    <h2>Регистрация</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>
{% endblock %}